import heroImage from "@/assets/hero-hotel.jpg";

const CITY_HERO_BASE = "/images/city-heroes-optimized";

const normalizeCitySlug = (citySlug: string): string => citySlug.toLowerCase();

/** Public WebP path for a city hero (generated by scripts/generate-city-heroes.ts). */
export const getCityHeroImagePath = (citySlug: string): string =>
  `${CITY_HERO_BASE}/${normalizeCitySlug(citySlug)}.webp`;

/** Responsive srcset: 960w mobile + 1600w desktop variants. */
export const getCityHeroSrcSet = (citySlug: string): string => {
  const slug = normalizeCitySlug(citySlug);
  return `${CITY_HERO_BASE}/${slug}-960.webp 960w, ${CITY_HERO_BASE}/${slug}.webp 1600w`;
};

export const CITY_HERO_SIZES = "100vw";

export const getDestinationHeroFallback = (): string => heroImage;

/**
 * Prefer optimized city heroes in public/images/city-heroes-optimized/{slug}.webp.
 * LandingHero should use onError to fall back to getDestinationHeroFallback().
 */
export const getDestinationHeroImage = (citySlug: string): string =>
  getCityHeroImagePath(citySlug);

export { heroImage as defaultHeroImage };
