import heroImage from "@/assets/hero-hotel.jpg";

const CITY_HERO_BASE = "/images/city-heroes";

/** Public WebP path for a city hero (generated by scripts/generate-city-heroes.ts). */
export const getCityHeroImagePath = (citySlug: string): string =>
  `${CITY_HERO_BASE}/${citySlug.toLowerCase()}.webp`;

export const getDestinationHeroFallback = (): string => heroImage;

/**
 * Prefer generated city heroes in public/images/city-heroes/{slug}.webp.
 * LandingHero should use onError to fall back to getDestinationHeroFallback().
 */
export const getDestinationHeroImage = (citySlug: string): string =>
  getCityHeroImagePath(citySlug);

export { heroImage as defaultHeroImage };
