/** Autocomplete-friendly queries for the top 100 global leisure destinations. */
export const SPIDER_TOURIST_CITIES = [
  "Paris, France",
  "London, United Kingdom",
  "Dubai, United Arab Emirates",
  "Rome, Italy",
  "New York City, New York, United States",
  "Tokyo, Japan",
  "Istanbul, Turkey",
  "Bangkok, Thailand",
  "Barcelona, Spain",
  "Amsterdam, Netherlands",
  "Milan, Italy",
  "Singapore",
  "Hong Kong",
  "Madrid, Spain",
  "Los Angeles, California, United States",
  "Prague, Czech Republic",
  "Vienna, Austria",
  "Munich, Germany",
  "Berlin, Germany",
  "Lisbon, Portugal",
  "Seoul, South Korea",
  "Florence, Italy",
  "Venice, Italy",
  "Dublin, Ireland",
  "Athens, Greece",
  "Las Vegas, Nevada, United States",
  "Miami, Florida, United States",
  "Orlando, Florida, United States",
  "San Francisco, California, United States",
  "Chicago, Illinois, United States",
  "Washington, District of Columbia, United States",
  "Boston, Massachusetts, United States",
  "Seattle, Washington, United States",
  "Honolulu, Hawaii, United States",
  "Cancun, Mexico",
  "Mexico City, Mexico",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Bali, Indonesia",
  "Phuket, Thailand",
  "Marrakech, Morocco",
  "Cape Town, South Africa",
  "Cairo, Egypt",
  "Jerusalem, Israel",
  "Tel Aviv, Israel",
  "Doha, Qatar",
  "Abu Dhabi, United Arab Emirates",
  "Shanghai, China",
  "Beijing, China",
  "Kyoto, Japan",
  "Osaka, Japan",
  "Taipei, Taiwan",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Manila, Philippines",
  "Edinburgh, United Kingdom",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Brussels, Belgium",
  "Copenhagen, Denmark",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Budapest, Hungary",
  "Krakow, Poland",
  "Warsaw, Poland",
  "Dubrovnik, Croatia",
  "Split, Croatia",
  "Santorini, Greece",
  "Mykonos, Greece",
  "Nice, France",
  "Cannes, France",
  "Monaco",
  "Interlaken, Switzerland",
  "Salzburg, Austria",
  "Bruges, Belgium",
  "Porto, Portugal",
  "Seville, Spain",
  "Granada, Spain",
  "Ibiza, Spain",
  "Palma de Mallorca, Spain",
  "Reykjavik, Iceland",
  "Montreal, Canada",
  "Vancouver, Canada",
  "Toronto, Canada",
  "Quebec City, Canada",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Lima, Peru",
  "Cusco, Peru",
  "Cartagena, Colombia",
  "Punta Cana, Dominican Republic",
  "San Juan, Puerto Rico",
  "New Orleans, Louisiana, United States",
  "Nashville, Tennessee, United States",
  "San Diego, California, United States",
  "Queenstown, New Zealand",
  "Maldives",
] as const;

export const pickRandomSpiderDestination = (): string => {
  const index = Math.floor(Math.random() * SPIDER_TOURIST_CITIES.length);
  return SPIDER_TOURIST_CITIES[index] ?? SPIDER_TOURIST_CITIES[0];
};
