import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSpiderUsDestinations } from "./spider-us-cities-by-state.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const destinations = buildSpiderUsDestinations();

const formatDestinationsSource = (): string => {
  const lines = destinations.map(
    ({ query, weight }) => `  { query: ${JSON.stringify(query)}, weight: ${weight} },`
  );
  return `export type SpiderTouristDestination = { readonly query: string; readonly weight: number };

/** US-only Kayak queries for GET /s/:token. Generated by npm run build:spider-cities. */
export const SPIDER_TOURIST_CITIES: readonly SpiderTouristDestination[] = [
${lines.join("\n")}
] as const;
`;
};

const spiderUsCitiesPath = join(root, "server/spider/spiderUsCities.ts");
writeFileSync(spiderUsCitiesPath, formatDestinationsSource(), "utf8");

const apiPath = join(root, "api/spider/[token].ts");
const apiSource = readFileSync(apiPath, "utf8");
const begin = "// BEGIN SPIDER_TOURIST_CITIES";
const end = "// END SPIDER_TOURIST_CITIES";
const block = `${begin}
type SpiderTouristDestination = { readonly query: string; readonly weight: number };

const SPIDER_TOURIST_CITIES: readonly SpiderTouristDestination[] = [
${destinations.map(({ query, weight }) => `  { query: ${JSON.stringify(query)}, weight: ${weight} },`).join("\n")}
] as const;
${end}`;

const pattern = new RegExp(
  `${begin}[\\s\\S]*?${end}`,
  "m"
);
if (!pattern.test(apiSource)) {
  throw new Error(
    `Missing ${begin} / ${end} markers in api/spider/[token].ts — add them around SPIDER_TOURIST_CITIES first.`
  );
}
writeFileSync(apiPath, apiSource.replace(pattern, block), "utf8");

console.log(
  `Wrote ${destinations.length} weighted US destinations to server/spider/spiderUsCities.ts and api/spider/[token].ts`
);
