export type SpiderUsCitySeed = {
  name: string;
  /** Default 10 when omitted. Major metros override via MAJOR_CITY_QUERY_WEIGHTS. */
  weight?: number;
};

/** Kayak autocomplete query → weight (higher = more likely for /s). */
export const MAJOR_CITY_QUERY_WEIGHTS: Record<string, number> = {
  "New York City, New York, United States": 100,
  "Los Angeles, California, United States": 98,
  "Chicago, Illinois, United States": 92,
  "Houston, Texas, United States": 88,
  "Phoenix, Arizona, United States": 85,
  "Philadelphia, Pennsylvania, United States": 82,
  "San Antonio, Texas, United States": 78,
  "San Diego, California, United States": 88,
  "Dallas, Texas, United States": 86,
  "Austin, Texas, United States": 84,
  "Jacksonville, Florida, United States": 72,
  "San Jose, California, United States": 80,
  "Fort Worth, Texas, United States": 70,
  "Columbus, Ohio, United States": 68,
  "Charlotte, North Carolina, United States": 76,
  "Indianapolis, Indiana, United States": 65,
  "San Francisco, California, United States": 95,
  "Seattle, Washington, United States": 90,
  "Denver, Colorado, United States": 82,
  "Washington, District of Columbia, United States": 94,
  "Boston, Massachusetts, United States": 91,
  "Nashville, Tennessee, United States": 86,
  "Las Vegas, Nevada, United States": 96,
  "Orlando, Florida, United States": 93,
  "Miami, Florida, United States": 94,
  "Atlanta, Georgia, United States": 87,
  "New Orleans, Louisiana, United States": 80,
  "Honolulu, Hawaii, United States": 85,
  "Portland, Oregon, United States": 75,
  "Minneapolis, Minnesota, United States": 72,
  "Detroit, Michigan, United States": 68,
  "Tampa, Florida, United States": 78,
  "St. Louis, Missouri, United States": 70,
  "Salt Lake City, Utah, United States": 74,
  "Brooklyn, New York, United States": 88,
};

export const SPIDER_US_CITIES_BY_STATE: Record<string, readonly SpiderUsCitySeed[]> = {
  Alabama: [
    { name: "Birmingham", weight: 22 },
    { name: "Montgomery" },
    { name: "Mobile", weight: 18 },
    { name: "Huntsville", weight: 20 },
    { name: "Tuscaloosa" },
    { name: "Hoover" },
    { name: "Auburn" },
    { name: "Decatur" },
    { name: "Madison" },
    { name: "Florence" },
  ],
  Alaska: [
    { name: "Anchorage", weight: 35 },
    { name: "Fairbanks", weight: 18 },
    { name: "Juneau" },
    { name: "Sitka" },
    { name: "Ketchikan" },
    { name: "Wasilla" },
    { name: "Kenai" },
  ],
  Arizona: [
    { name: "Phoenix", weight: 85 },
    { name: "Scottsdale", weight: 55 },
    { name: "Tucson", weight: 45 },
    { name: "Sedona", weight: 40 },
    { name: "Flagstaff", weight: 28 },
    { name: "Mesa", weight: 38 },
    { name: "Tempe", weight: 32 },
    { name: "Chandler", weight: 30 },
    { name: "Glendale", weight: 28 },
    { name: "Prescott" },
    { name: "Yuma" },
    { name: "Lake Havasu City" },
  ],
  Arkansas: [
    { name: "Little Rock", weight: 22 },
    { name: "Fayetteville", weight: 20 },
    { name: "Fort Smith" },
    { name: "Springdale" },
    { name: "Hot Springs", weight: 25 },
    { name: "Bentonville", weight: 24 },
    { name: "Rogers" },
  ],
  California: [
    { name: "Los Angeles", weight: 98 },
    { name: "San Francisco", weight: 95 },
    { name: "San Diego", weight: 88 },
    { name: "San Jose", weight: 80 },
    { name: "Sacramento", weight: 42 },
    { name: "Oakland", weight: 38 },
    { name: "Anaheim", weight: 45 },
    { name: "Santa Barbara", weight: 48 },
    { name: "Napa", weight: 50 },
    { name: "Monterey", weight: 40 },
    { name: "Palm Springs", weight: 45 },
    { name: "South Lake Tahoe", weight: 38 },
    { name: "Fresno", weight: 28 },
    { name: "Long Beach", weight: 35 },
    { name: "Irvine", weight: 36 },
    { name: "Santa Monica", weight: 42 },
    { name: "Berkeley", weight: 30 },
    { name: "Malibu", weight: 35 },
    { name: "Santa Cruz", weight: 28 },
    { name: "Pasadena", weight: 32 },
    { name: "Bakersfield", weight: 22 },
    { name: "Riverside", weight: 26 },
    { name: "Stockton" },
    { name: "Modesto" },
    { name: "San Luis Obispo", weight: 26 },
    { name: "Big Sur", weight: 30 },
    { name: "Carmel-by-the-Sea", weight: 28 },
    { name: "Sonoma", weight: 32 },
    { name: "Healdsburg", weight: 24 },
    { name: "Carlsbad", weight: 28 },
    { name: "Coronado", weight: 26 },
    { name: "Laguna Beach", weight: 30 },
    { name: "Newport Beach", weight: 32 },
    { name: "Huntington Beach", weight: 28 },
    { name: "Manhattan Beach", weight: 26 },
    { name: "Redwood City", weight: 24 },
    { name: "Mountain View", weight: 28 },
    { name: "Palo Alto", weight: 30 },
    { name: "Cupertino" },
    { name: "Santa Clara", weight: 26 },
    { name: "Sunnyvale", weight: 24 },
    { name: "San Mateo" },
    { name: "Daly City" },
    { name: "Mill Valley" },
    { name: "Sausalito", weight: 22 },
    { name: "Half Moon Bay" },
    { name: "Mammoth Lakes", weight: 28 },
    { name: "Joshua Tree", weight: 26 },
    { name: "Palm Desert", weight: 24 },
    { name: "La Jolla", weight: 30 },
  ],
  Colorado: [
    { name: "Denver", weight: 82 },
    { name: "Colorado Springs", weight: 35 },
    { name: "Boulder", weight: 40 },
    { name: "Aspen", weight: 45 },
    { name: "Vail", weight: 48 },
    { name: "Breckenridge", weight: 42 },
    { name: "Steamboat Springs", weight: 38 },
    { name: "Fort Collins", weight: 28 },
    { name: "Durango", weight: 24 },
    { name: "Telluride", weight: 36 },
    { name: "Estes Park", weight: 26 },
    { name: "Grand Junction" },
    { name: "Pueblo" },
    { name: "Loveland" },
    { name: "Glenwood Springs", weight: 22 },
  ],
  Connecticut: [
    { name: "Hartford", weight: 22 },
    { name: "New Haven", weight: 24 },
    { name: "Stamford", weight: 26 },
    { name: "Bridgeport" },
    { name: "Norwalk" },
    { name: "Greenwich", weight: 28 },
    { name: "Mystic", weight: 24 },
    { name: "New London" },
  ],
  Delaware: [
    { name: "Wilmington", weight: 20 },
    { name: "Dover" },
    { name: "Rehoboth Beach", weight: 26 },
    { name: "Lewes" },
    { name: "Newark" },
  ],
  "District of Columbia": [{ name: "Washington", weight: 94 }],
  Florida: [
    { name: "Miami", weight: 94 },
    { name: "Miami Beach", weight: 55 },
    { name: "Orlando", weight: 93 },
    { name: "Tampa", weight: 78 },
    { name: "St. Petersburg", weight: 32 },
    { name: "Jacksonville", weight: 72 },
    { name: "Fort Lauderdale", weight: 52 },
    { name: "West Palm Beach", weight: 38 },
    { name: "Naples", weight: 42 },
    { name: "Sarasota", weight: 36 },
    { name: "Key West", weight: 40 },
    { name: "Destin", weight: 35 },
    { name: "Panama City Beach", weight: 28 },
    { name: "Clearwater", weight: 30 },
    { name: "Daytona Beach", weight: 26 },
    { name: "St. Augustine", weight: 28 },
    { name: "Fort Myers", weight: 32 },
    { name: "Pensacola", weight: 24 },
    { name: "Tallahassee" },
    { name: "Gainesville" },
    { name: "Boca Raton", weight: 30 },
    { name: "Delray Beach", weight: 26 },
    { name: "Hollywood", weight: 24 },
    { name: "Coral Gables", weight: 22 },
    { name: "Marco Island", weight: 28 },
    { name: "Amelia Island", weight: 24 },
    { name: "Vero Beach" },
    { name: "Melbourne", weight: 20 },
    { name: "Kissimmee", weight: 35 },
    { name: "Lakeland" },
  ],
  Georgia: [
    { name: "Atlanta", weight: 87 },
    { name: "Savannah", weight: 45 },
    { name: "Augusta", weight: 22 },
    { name: "Athens", weight: 24 },
    { name: "Macon" },
    { name: "Columbus" },
    { name: "Alpharetta", weight: 26 },
    { name: "Roswell" },
    { name: "Marietta" },
    { name: "Tybee Island", weight: 22 },
    { name: "Jekyll Island", weight: 24 },
    { name: "Blue Ridge", weight: 20 },
  ],
  Hawaii: [
    { name: "Honolulu", weight: 85 },
    { name: "Waikiki", weight: 55 },
    { name: "Lahaina", weight: 40 },
    { name: "Kailua-Kona", weight: 38 },
    { name: "Hilo", weight: 24 },
    { name: "Kihei", weight: 28 },
    { name: "Kapaa" },
    { name: "Poipu", weight: 26 },
    { name: "Princeville", weight: 24 },
    { name: "Lihue" },
  ],
  Idaho: [
    { name: "Boise", weight: 32 },
    { name: "Idaho Falls" },
    { name: "Coeur d'Alene", weight: 24 },
    { name: "Sun Valley", weight: 30 },
    { name: "McCall", weight: 20 },
    { name: "Twin Falls" },
  ],
  Illinois: [
    { name: "Chicago", weight: 92 },
    { name: "Springfield" },
    { name: "Naperville", weight: 28 },
    { name: "Evanston", weight: 24 },
    { name: "Oak Park" },
    { name: "Galena", weight: 22 },
    { name: "Peoria" },
    { name: "Rockford" },
    { name: "Champaign" },
    { name: "Urbana" },
    { name: "Schaumburg" },
    { name: "Arlington Heights" },
  ],
  Indiana: [
    { name: "Indianapolis", weight: 65 },
    { name: "Fort Wayne", weight: 22 },
    { name: "Bloomington", weight: 24 },
    { name: "South Bend", weight: 22 },
    { name: "Evansville" },
    { name: "Carmel", weight: 20 },
    { name: "Crown Point" },
  ],
  Iowa: [
    { name: "Des Moines", weight: 28 },
    { name: "Cedar Rapids" },
    { name: "Iowa City", weight: 22 },
    { name: "Davenport" },
    { name: "Sioux City" },
    { name: "Ames" },
  ],
  Kansas: [
    { name: "Wichita", weight: 24 },
    { name: "Kansas City", weight: 35 },
    { name: "Overland Park", weight: 26 },
    { name: "Topeka" },
    { name: "Lawrence", weight: 20 },
    { name: "Manhattan" },
  ],
  Kentucky: [
    { name: "Louisville", weight: 38 },
    { name: "Lexington", weight: 28 },
    { name: "Bowling Green" },
    { name: "Frankfort" },
    { name: "Covington" },
    { name: "Paducah" },
    { name: "Mammoth Cave", weight: 22 },
  ],
  Louisiana: [
    { name: "New Orleans", weight: 80 },
    { name: "Baton Rouge", weight: 24 },
    { name: "Lafayette" },
    { name: "Shreveport" },
    { name: "Lake Charles" },
    { name: "Alexandria" },
    { name: "Monroe" },
  ],
  Maine: [
    { name: "Portland", weight: 28 },
    { name: "Bar Harbor", weight: 26 },
    { name: "Kennebunkport", weight: 24 },
    { name: "Camden", weight: 22 },
    { name: "Rockland" },
    { name: "Bangor" },
    { name: "Freeport" },
    { name: "Ogunquit", weight: 22 },
  ],
  Maryland: [
    { name: "Baltimore", weight: 42 },
    { name: "Annapolis", weight: 24 },
    { name: "Ocean City", weight: 28 },
    { name: "Frederick" },
    { name: "Bethesda", weight: 26 },
    { name: "Silver Spring" },
    { name: "Rockville" },
    { name: "National Harbor", weight: 24 },
  ],
  Massachusetts: [
    { name: "Boston", weight: 91 },
    { name: "Cambridge", weight: 38 },
    { name: "Salem", weight: 24 },
    { name: "Cape Cod", weight: 40 },
    { name: "Provincetown", weight: 28 },
    { name: "Nantucket", weight: 35 },
    { name: "Martha's Vineyard", weight: 36 },
    { name: "Worcester", weight: 22 },
    { name: "Springfield" },
    { name: "Plymouth", weight: 20 },
    { name: "Lexington" },
    { name: "Concord" },
    { name: "Lenox", weight: 22 },
  ],
  Michigan: [
    { name: "Detroit", weight: 68 },
    { name: "Grand Rapids", weight: 28 },
    { name: "Ann Arbor", weight: 30 },
    { name: "Traverse City", weight: 32 },
    { name: "Mackinac Island", weight: 28 },
    { name: "Lansing" },
    { name: "Flint" },
    { name: "Kalamazoo" },
    { name: "Holland", weight: 22 },
    { name: "Petoskey", weight: 20 },
  ],
  Minnesota: [
    { name: "Minneapolis", weight: 72 },
    { name: "St. Paul", weight: 35 },
    { name: "Duluth", weight: 22 },
    { name: "Rochester", weight: 24 },
    { name: "Bloomington", weight: 22 },
    { name: "Stillwater" },
    { name: "Brainerd", weight: 20 },
  ],
  Mississippi: [
    { name: "Jackson" },
    { name: "Biloxi", weight: 24 },
    { name: "Gulfport" },
    { name: "Hattiesburg" },
    { name: "Oxford", weight: 20 },
    { name: "Natchez", weight: 18 },
    { name: "Tupelo" },
  ],
  Missouri: [
    { name: "Kansas City", weight: 55 },
    { name: "St. Louis", weight: 70 },
    { name: "Springfield" },
    { name: "Branson", weight: 30 },
    { name: "Columbia", weight: 20 },
    { name: "Jefferson City" },
    { name: "Lake of the Ozarks", weight: 24 },
    { name: "St. Charles" },
  ],
  Montana: [
    { name: "Billings", weight: 20 },
    { name: "Missoula", weight: 22 },
    { name: "Bozeman", weight: 26 },
    { name: "Whitefish", weight: 28 },
    { name: "Big Sky", weight: 30 },
    { name: "Helena" },
    { name: "Great Falls" },
    { name: "Glacier National Park", weight: 26 },
  ],
  Nebraska: [
    { name: "Omaha", weight: 28 },
    { name: "Lincoln", weight: 20 },
    { name: "Grand Island" },
    { name: "Kearney" },
    { name: "Scottsbluff" },
  ],
  Nevada: [
    { name: "Las Vegas", weight: 96 },
    { name: "Reno", weight: 38 },
    { name: "Lake Tahoe", weight: 42 },
    { name: "Henderson", weight: 32 },
    { name: "North Las Vegas" },
    { name: "Sparks" },
    { name: "Carson City" },
    { name: "Boulder City", weight: 22 },
  ],
  "New Hampshire": [
    { name: "Manchester", weight: 22 },
    { name: "Portsmouth", weight: 24 },
    { name: "Concord" },
    { name: "North Conway", weight: 22 },
    { name: "Keene" },
    { name: "Hanover", weight: 20 },
    { name: "Lincoln", weight: 22 },
  ],
  "New Jersey": [
    { name: "Newark", weight: 35 },
    { name: "Jersey City", weight: 32 },
    { name: "Atlantic City", weight: 38 },
    { name: "Princeton", weight: 26 },
    { name: "Hoboken", weight: 28 },
    { name: "Cape May", weight: 24 },
    { name: "Asbury Park", weight: 22 },
    { name: "Montclair" },
    { name: "Trenton" },
    { name: "Paterson" },
  ],
  "New Mexico": [
    { name: "Albuquerque", weight: 32 },
    { name: "Santa Fe", weight: 40 },
    { name: "Taos", weight: 28 },
    { name: "Las Cruces" },
    { name: "Roswell", weight: 18 },
    { name: "Carlsbad", weight: 16 },
    { name: "Silver City" },
  ],
  "New York": [
    { name: "New York City", weight: 100 },
    { name: "Brooklyn", weight: 88 },
    { name: "Buffalo", weight: 28 },
    { name: "Rochester", weight: 22 },
    { name: "Albany", weight: 20 },
    { name: "Syracuse", weight: 22 },
    { name: "Ithaca", weight: 20 },
    { name: "Lake Placid", weight: 24 },
    { name: "Saratoga Springs", weight: 22 },
    { name: "Niagara Falls", weight: 35 },
    { name: "The Hamptons", weight: 38 },
    { name: "Montauk", weight: 30 },
    { name: "Cooperstown" },
    { name: "Kingston" },
    { name: "Poughkeepsie" },
    { name: "White Plains", weight: 24 },
    { name: "Yonkers", weight: 26 },
    { name: "Long Island City", weight: 32 },
  ],
  "North Carolina": [
    { name: "Charlotte", weight: 76 },
    { name: "Raleigh", weight: 45 },
    { name: "Asheville", weight: 40 },
    { name: "Wilmington", weight: 32 },
    { name: "Durham", weight: 38 },
    { name: "Chapel Hill", weight: 28 },
    { name: "Greensboro", weight: 24 },
    { name: "Winston-Salem", weight: 22 },
    { name: "Outer Banks", weight: 30 },
    { name: "Boone", weight: 22 },
    { name: "Highlands", weight: 20 },
    { name: "Blowing Rock", weight: 20 },
    { name: "Fayetteville" },
    { name: "Cary", weight: 26 },
  ],
  "North Dakota": [
    { name: "Fargo", weight: 18 },
    { name: "Bismarck" },
    { name: "Grand Forks" },
    { name: "Minot" },
    { name: "Medora", weight: 16 },
  ],
  Ohio: [
    { name: "Columbus", weight: 68 },
    { name: "Cleveland", weight: 42 },
    { name: "Cincinnati", weight: 45 },
    { name: "Dayton", weight: 24 },
    { name: "Toledo", weight: 20 },
    { name: "Akron" },
    { name: "Canton" },
    { name: "Youngstown" },
    { name: "Sandusky", weight: 22 },
    { name: "Put-in-Bay", weight: 18 },
  ],
  Oklahoma: [
    { name: "Oklahoma City", weight: 32 },
    { name: "Tulsa", weight: 28 },
    { name: "Norman", weight: 20 },
    { name: "Broken Arrow" },
    { name: "Stillwater" },
    { name: "Lawton" },
  ],
  Oregon: [
    { name: "Portland", weight: 75 },
    { name: "Eugene", weight: 24 },
    { name: "Bend", weight: 32 },
    { name: "Salem", weight: 20 },
    { name: "Corvallis" },
    { name: "Ashland", weight: 22 },
    { name: "Cannon Beach", weight: 24 },
    { name: "Hood River", weight: 22 },
    { name: "Crater Lake", weight: 26 },
    { name: "Newport", weight: 18 },
  ],
  Pennsylvania: [
    { name: "Philadelphia", weight: 82 },
    { name: "Pittsburgh", weight: 45 },
    { name: "Harrisburg", weight: 18 },
    { name: "Lancaster", weight: 22 },
    { name: "Gettysburg", weight: 24 },
    { name: "Allentown", weight: 22 },
    { name: "Erie" },
    { name: "Scranton" },
    { name: "State College", weight: 22 },
    { name: "Reading" },
    { name: "York" },
    { name: "Bethlehem", weight: 18 },
  ],
  "Rhode Island": [
    { name: "Providence", weight: 28 },
    { name: "Newport", weight: 32 },
    { name: "Warwick" },
    { name: "Cranston" },
    { name: "Block Island", weight: 24 },
  ],
  "South Carolina": [
    { name: "Charleston", weight: 48 },
    { name: "Columbia", weight: 26 },
    { name: "Greenville", weight: 28 },
    { name: "Myrtle Beach", weight: 40 },
    { name: "Hilton Head Island", weight: 38 },
    { name: "Beaufort", weight: 22 },
    { name: "Spartanburg" },
    { name: "Mount Pleasant", weight: 24 },
    { name: "Kiawah Island", weight: 28 },
  ],
  "South Dakota": [
    { name: "Sioux Falls", weight: 20 },
    { name: "Rapid City", weight: 24 },
    { name: "Deadwood", weight: 20 },
    { name: "Sturgis", weight: 18 },
    { name: "Pierre" },
    { name: "Mount Rushmore", weight: 22 },
  ],
  Tennessee: [
    { name: "Nashville", weight: 86 },
    { name: "Memphis", weight: 42 },
    { name: "Knoxville", weight: 32 },
    { name: "Chattanooga", weight: 30 },
    { name: "Gatlinburg", weight: 38 },
    { name: "Pigeon Forge", weight: 36 },
    { name: "Franklin", weight: 24 },
    { name: "Clarksville" },
    { name: "Murfreesboro", weight: 22 },
    { name: "Johnson City" },
  ],
  Texas: [
    { name: "Houston", weight: 88 },
    { name: "Dallas", weight: 86 },
    { name: "Austin", weight: 84 },
    { name: "San Antonio", weight: 78 },
    { name: "Fort Worth", weight: 70 },
    { name: "El Paso", weight: 32 },
    { name: "Galveston", weight: 35 },
    { name: "Corpus Christi", weight: 28 },
    { name: "South Padre Island", weight: 30 },
    { name: "Fredericksburg", weight: 24 },
    { name: "Marble Falls", weight: 20 },
    { name: "Amarillo", weight: 20 },
    { name: "Lubbock", weight: 22 },
    { name: "Waco", weight: 20 },
    { name: "College Station", weight: 22 },
    { name: "Plano", weight: 28 },
    { name: "Frisco", weight: 26 },
    { name: "Arlington", weight: 32 },
    { name: "Irving", weight: 24 },
    { name: "McAllen", weight: 20 },
    { name: "Laredo" },
    { name: "Tyler" },
    { name: "Abilene" },
    { name: "Midland", weight: 22 },
    { name: "Odessa" },
    { name: "Beaumont" },
    { name: "Port Aransas", weight: 22 },
    { name: "Round Rock", weight: 22 },
    { name: "San Marcos", weight: 20 },
    { name: "Denton", weight: 20 },
  ],
  Utah: [
    { name: "Salt Lake City", weight: 74 },
    { name: "Park City", weight: 45 },
    { name: "Moab", weight: 38 },
    { name: "St. George", weight: 26 },
    { name: "Provo", weight: 24 },
    { name: "Ogden", weight: 20 },
    { name: "Zion National Park", weight: 32 },
    { name: "Bryce Canyon City", weight: 24 },
    { name: "Logan" },
  ],
  Vermont: [
    { name: "Burlington", weight: 24 },
    { name: "Stowe", weight: 30 },
    { name: "Montpelier" },
    { name: "Killington", weight: 26 },
    { name: "Woodstock", weight: 22 },
    { name: "Manchester", weight: 20 },
    { name: "Bennington" },
  ],
  Virginia: [
    { name: "Virginia Beach", weight: 38 },
    { name: "Norfolk", weight: 28 },
    { name: "Richmond", weight: 32 },
    { name: "Arlington", weight: 40 },
    { name: "Alexandria", weight: 36 },
    { name: "Charlottesville", weight: 28 },
    { name: "Williamsburg", weight: 30 },
    { name: "Roanoke", weight: 20 },
    { name: "Fredericksburg", weight: 22 },
    { name: "Lynchburg" },
    { name: "Winchester", weight: 18 },
    { name: "Shenandoah", weight: 24 },
  ],
  Washington: [
    { name: "Seattle", weight: 90 },
    { name: "Spokane", weight: 26 },
    { name: "Tacoma", weight: 24 },
    { name: "Bellevue", weight: 30 },
    { name: "Olympia" },
    { name: "Bellingham", weight: 22 },
    { name: "Leavenworth", weight: 26 },
    { name: "Port Angeles", weight: 20 },
    { name: "Walla Walla", weight: 18 },
    { name: "Whidbey Island", weight: 22 },
    { name: "San Juan Islands", weight: 24 },
    { name: "Mount Rainier", weight: 22 },
  ],
  "West Virginia": [
    { name: "Charleston", weight: 16 },
    { name: "Morgantown", weight: 18 },
    { name: "Huntington" },
    { name: "Wheeling" },
    { name: "Harper's Ferry", weight: 20 },
    { name: "Lewisburg" },
  ],
  Wisconsin: [
    { name: "Milwaukee", weight: 38 },
    { name: "Madison", weight: 32 },
    { name: "Green Bay", weight: 24 },
    { name: "Wisconsin Dells", weight: 28 },
    { name: "Door County", weight: 26 },
    { name: "Lake Geneva", weight: 24 },
    { name: "Appleton" },
    { name: "Eau Claire" },
    { name: "La Crosse" },
  ],
  Wyoming: [
    { name: "Cheyenne", weight: 16 },
    { name: "Jackson", weight: 35 },
    { name: "Cody", weight: 22 },
    { name: "Laramie", weight: 16 },
    { name: "Gillette" },
    { name: "Yellowstone National Park", weight: 30 },
    { name: "Grand Teton", weight: 28 },
  ],
};

export const formatSpiderUsCityQuery = (city: string, state: string): string =>
  `${city}, ${state}, United States`;

const DEFAULT_CITY_WEIGHT = 10;

export type BuiltSpiderDestination = { query: string; weight: number };

export const buildSpiderUsDestinations = (): BuiltSpiderDestination[] => {
  const byQuery = new Map<string, number>();

  for (const [state, cities] of Object.entries(SPIDER_US_CITIES_BY_STATE)) {
    for (const entry of cities) {
      const query = formatSpiderUsCityQuery(entry.name, state);
      const seedWeight = entry.weight ?? DEFAULT_CITY_WEIGHT;
      const majorWeight = MAJOR_CITY_QUERY_WEIGHTS[query];
      const weight = Math.max(seedWeight, majorWeight ?? 0);
      const existing = byQuery.get(query);
      byQuery.set(query, existing === undefined ? weight : Math.max(existing, weight));
    }
  }

  return [...byQuery.entries()]
    .map(([query, weight]) => ({ query, weight }))
    .sort((a, b) => a.query.localeCompare(b.query));
};
